meta_product_name: "Scuba Libre"
meta_title: "Discover the underwater world wherever you are"
meta_description: "Get in touch with Scuba Diving Instructors all around the world  "
meta_image: "cover.jpg" # should exist in `app/assets/images/`
